let str = 'hey';
console.log(str.reverse());


function checker(){
str.split()


}

var str = 'The quick brown fox jumps over the lazy dog.';

var words = str.split('');
console.log(words)


function checker(){
let str = 'racecar';
let rev = str.split('').reverse().join('');

console.log(rev);

    if(str == rev){
        console.log(true);
    } else {
        console.log(false);
    }
}
checker();